/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  aivesa: [
    'welcome',
    {
      type: 'category',
      label: '💡 About Aivesa',
      link: {
        type: 'generated-index',
        description: '这里将简单介绍 Aivesa',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'aivesa',
        },
      ],
    },
  ],
  llm: [
    {
      type: 'autogenerated',
      dirName: 'llm',
    },
  ],
  midjourney: [
    {
      type: 'autogenerated',
      dirName: 'midjourney',
    },
  ],
}

module.exports = sidebars